(function(){
  var test = require('coba');
  
  var input;
  // Remove try & catch lines if you don't want to use data that 
  // generated by coba
  try{
    input = require(process.cwd()+'/data.json');  
  }catch($e){
    return console.log($e.message);
  }
    
  test.run(input,function(driver,input,output){
    // fill input bisa
  })
  
}).call(this);